---
- hosts: all
  tasks:
   - name: Create Ping job template
     job_template:
       name: "Ping"
       job_type: "run"
       organization: "Default"
       inventory: "Local"
       project: "Demo"
       playbook: "ping.yml"
       verbosity: 0
       credentials:
         - "host_aap
       state: "present"
