---
- hosts: all
  tasks:
   - name: Create job template
     ansible.controller.job_template:
       name: "Controller_test"
       controller_host: vm253-172.gsslab.pnq2.redhat.com
       controller_username: admin
       controller_password: admin
       job_type: "run"
       organization: "Default"
       inventory: "controller"
       project: "AAP"
       playbook: "debug.yml"
       verbosity: 3
       credentials: "controller"
       state: "present"
       validate_certs: false
