---
- hosts: all
  tasks:
   - name: Create job template
     job_template:
       name: "Controller_test"
       job_type: "run"
       organization: "Default"
       inventory: "controller"
       project: "AAP"
       playbook: "aap_job_template.yml"
       verbosity: 0
       credentials: "controller"
       state: "present"
