- name: show fact variable
  hosts: all
  tasks:
     - name: Print the fact variable value
       ansible.builtin.debug:
           msg: System hostname {{ansible_managed}}

     - name: System running sleep command
       ansible.builtin.shell: sleep 2000
