- name: show fact variable
  hosts: all
  tasks:
     - name: Print the fact variable value
       ansible.builtin.debug:
           msg: System hostname {{ansible_managed}}

     - name: run sudo
       ansible.builtin.command: sudo su - nikhil
